apiVersion: v1
kind: Service
metadata:
  name: {{ include "techtrends.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ include "techtrends.fullname" . }}
  type: {{ .Values.service.type }}
